version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Docker/web/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/LoanCalculatorDocker
    env_file:
      - .env
